spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:15432/miniminimoney
spring.datasource.username=admin
spring.datasource.password=abc123
spring.security.user.name=dingding
spring.security.user.password=abc123

spring.flyway.locations=classpath:/db/migration

spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000
