
CREATE SEQUENCE s_transaction START WITH 1 INCREMENT BY 1 CACHE 50 NO CYCLE;
CREATE SEQUENCE s_asset START WITH 1 INCREMENT BY 1 CACHE 50 NO CYCLE;
CREATE SEQUENCE s_debt START WITH 1 INCREMENT BY 1 CACHE 50 NO CYCLE;
CREATE SEQUENCE s_loan START WITH 1 INCREMENT BY 1 CACHE 50 NO CYCLE;